# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
watch:
  - .trmnlp.yml
  - src

custom_fields:
  country: "10YNL----------L"
  price_unit: "currency_kwh"
  usage_examples: ""
  vat_percent: "0"


# The transform needs a real zone to slice out "today" correctly.
time_zone: Europe/Amsterdam

transform_runtime: enabled

variables:
  trmnl:
    plugin_settings:
      instance_name: Day-Ahead Prices
      polling_url: "http://localhost:5005/api/v1/energy-prices?bidding_zone={% if country == \"GB\" %}{{ gb_zone }}{% elsif country == \"IT\" %}{{ it_zone }}{% elsif country == \"DK\" %}{{ dk_zone }}{% elsif country == \"NOR\" %}{{ no_zone }}{% elsif country == \"SE\" %}{{ se_zone }}{% else %}{{ country }}{% endif %}&price_unit={{ price_unit }}&vat_percent={{ vat_percent }}&usage_examples={{ usage_examples | url_encode }}&tz={{ time_zone }}&utc_offset=utc_offset=7200"
